### ISSUE TITLE
Feedback on Test Cases

### ISSUE THREAD

**Issue by PBauer256** [HameedShirzay/Software-Testing-Automation-Portfolio#1]
Looks Great!
Lots of test cases with very good coverage.

Some comments:
Dont forget that you have other options than BVA and EP. You can use State Transition testing or Decision Table testing, to make an argument for test cases (e,g, 3.6) and use those techniques to make sure you have full coverage.

1.8) Is this Error guessing or BVA ? Looking at your first 2 test cases, I have a feeling that this is part of those Boundary Values. 
1.7) Is this test case covered by your requirements ? Does it make sense ?
1.9) Is this covered by your requirements ? 
3.6) I like the test case, but is it error guessing ?

**Comment by HameedShirzay** [comment]
I updated the mentioned points and removed some of them which was not covered by my requirements.
