### ISSUE TITLE
Project Setup Feedback

### ISSUE THREAD

**Issue by PBauer256** [HameedShirzay/Software-Testing-Automation-Portfolio#3]
Your Github Profile and the portfolio are just as important as your CV. Any future employer is going to look at it very critically. You need to make sure that it doesnt look copied or sloppy.

1) Your Github Profile itself looks slightly broken.
2) Please rename the portfolio. Its your portfolio, not any example portfolio. It just looks copied in this way.

**Comment by HameedShirzay** [comment]
I already update the readme and the Github profile.
