### ISSUE TITLE
Feedback on Bug Reporting

### ISSUE THREAD

**Issue by PBauer256** [HameedShirzay/Software-Testing-Automation-Portfolio#5]
As you have found some Test-Failures in your Test Execution, please add some Bugs to your issue page or create a new Page for bugs. Make sure it includes all the information needed by a developer to fix the bug and for everyone to understand exactly what the bug is and how to reproduce it.

Make sure to treat it professionally, considering your severities, exit criteria in the test plan etc.

**Comment by HameedShirzay** [comment]
i have added bug report.mg as a file is this enough?

**Comment by PBauer256** [comment]
absolutely, looks Good
